server:
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto:
    show-sql: true

  data:
    redis:
      host:
      port: 6379
      timeout: 60000

minio:
  url:
  accessKey:
  secretKey:
  bucketName: